config/routes.rb
Rails.application.routes.draw do

  root 'tickets#index'

  resources :vehicles

  resources :tickets

  resources :statuses

  resources :services

  resources :positions

  resources :employees

  resources :customers

  resources :categories

  resources :acts

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :tickets
  def emp_full_name
    "#{emp_first} #{emp_last}"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:emp_first, :emp_last, :emp_address, :emp_city, :emp_state, :emp_phone_string, :emp_email)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :emp_first %><br>
    <%= f.text_area :emp_first %>
  </div>
  <div class="field">
    <%= f.label :emp_last %><br>
    <%= f.text_area :emp_last %>
  </div>
  <div class="field">
    <%= f.label :emp_address %><br>
    <%= f.text_area :emp_address %>
  </div>
  <div class="field">
    <%= f.label :emp_city %><br>
    <%= f.text_area :emp_city %>
  </div>
  <div class="field">
    <%= f.label :emp_state %><br>
    <%= f.text_area :emp_state %>
  </div>
  <div class="field">
    <%= f.label :emp_phone_string %><br>
    <%= f.text_field :emp_phone_string %>
  </div>
  <div class="field">
    <%= f.label :emp_email %><br>
    <%= f.text_area :emp_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Emp first</th>
      <th>Emp last</th>
      <th>Emp address</th>
      <th>Emp city</th>
      <th>Emp state</th>
      <th>Emp phone string</th>
      <th>Emp email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.emp_first %></td>
        <td><%= employee.emp_last %></td>
        <td><%= employee.emp_address %></td>
        <td><%= employee.emp_city %></td>
        <td><%= employee.emp_state %></td>
        <td><%= employee.emp_phone_string %></td>
        <td><%= employee.emp_email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp first:</strong>
  <%= @employee.emp_first %>
</p>

<p>
  <strong>Emp last:</strong>
  <%= @employee.emp_last %>
</p>

<p>
  <strong>Emp address:</strong>
  <%= @employee.emp_address %>
</p>

<p>
  <strong>Emp city:</strong>
  <%= @employee.emp_city %>
</p>

<p>
  <strong>Emp state:</strong>
  <%= @employee.emp_state %>
</p>

<p>
  <strong>Emp phone string:</strong>
  <%= @employee.emp_phone_string %>
</p>

<p>
  <strong>Emp email:</strong>
  <%= @employee.emp_email %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>